baseURL = "https://uchicago-cs.github.io/cmsc22000/"
languageCode = "en-us"
title = "CS 220"
theme = "hyde-y"

[params]
topline = "Introduction to Software Development"
sidebar = "left"
googleAnalytics = "UA-27880910-4"

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 1
